Wie 19/careers page text
UNSW-WIESoc/website pull request #17
Opened 2024-06-13 09:14 UTC by DaisyYye

- Added 2 texts on the careers page. 
- (I think) fixed the mess I made in packages;-;

2024-06-20 06:00 UTC, angewen requested changes

2024-06-20 06:00 UTC, angewen commented on app/(pages)/careers/page.tsx
> +        <Typography level="h1" className="graphite">
font level h1 already defaults to graphite, see ThemeRegistry.tsx

2024-06-20 06:00 UTC, angewen commented on app/(pages)/careers/page.tsx
> +        <Typography level="body" className="graphite">
font level body already defaults to graphite

2024-06-22 03:32 UTC, sophiac6410 commented on app/(pages)/careers/page.tsx
> +      <Box mt={2} textAlign="center">
You can use the HeadingBodyText component for this section!

2024-07-04 06:18 UTC, sophiac6410 approved these changes

2024-07-04 06:40 UTC, angewen approved these changes

2024-07-04 06:40 UTC, merged