Wie 18/sponsors page
UNSW-WIESoc/website pull request #20
Opened 2024-06-16 12:07 UTC by Aur3lia

Completed Sponsors Page.

- Added SponsorSection into components file for implementing sponsor sub-headings
- Fixed Jane Street logo typo
- Added SponsorRows function for adding the different sponsor images in each section
- Added mobile responsiveness

2024-06-20 12:48 UTC, angewen requested changes
The sponsor logos could be smaller, they look very large on desktop lol

This size would be gd with a larger margins on the sides: (I just zoomed out on the page to 65%)
<img width="1440" alt="image" src="https://github.com/UNSW-WIESoc/website/assets/119286195/e443dcba-abad-400e-a8a0-85111cea20c3">


For comparison this is the current size at 100% on desktop:
<img width="1439" alt="image" src="https://github.com/UNSW-WIESoc/website/assets/119286195/a5950bc7-24a6-4ae4-8b8f-78b5f3aa803a">

2024-06-20 12:48 UTC, angewen commented on app/(pages)/sponsors/page.tsx
> +            paddingBottom: '20%',
try using pb as shorthand, it can be used outside of sx too `pb='20%'`

2024-06-20 12:48 UTC, angewen commented on components/SponsorSection.tsx
> +          mb: 5,
mt and mb can be outside of sx

2024-06-20 12:48 UTC, angewen commented on app/(pages)/sponsors/page.tsx
> +import { Box, Stack, Typography } from '@mui/joy';
unused import Typography

2024-06-20 12:48 UTC, angewen commented on app/(pages)/sponsors/page.tsx
> +          mx: 'auto',
mx can be outside sx

2024-06-20 12:56 UTC, angewen requested changes

2024-06-20 12:56 UTC, angewen commented on app/(pages)/sponsors/page.tsx
> +            sx= {{ width: { xs: '80%', sm: '65%', md: '85%', lg: '70%'} }}
Alot of code repetition for this Stack and its styling, perhaps make it a component

2024-06-22 05:27 UTC, sophiac6410 requested changes

2024-06-28 06:03 UTC, Aur3lia commented
Made changes to this PR:
- Used HorizontalLine component in SponsorSection component
- Fixed UNSW logo ratio
- Changed the other sponsors' image size
- Used Grid instead of Box to format the sponsor rows

2024-07-02 04:23 UTC, sophiac6410 approved these changes
looks great!

2024-07-02 06:17 UTC, angewen approved these changes

2024-07-02 15:52 UTC, merged