implemented mobile responsiveness for header card
UNSW-WIESoc/website pull request #28
Opened 2024-07-17 19:52 UTC by nnnwa76

Added page header card mobile responsiveness 

<img width="504" alt="Screenshot 2024-07-18 at 5 50 41 am" src="https://github.com/user-attachments/assets/56a9831f-c210-4878-90ef-c6cac032aaef">
<img width="1247" alt="Screenshot 2024-07-18 at 5 50 31 am" src="https://github.com/user-attachments/assets/a0781d93-c06e-449c-8db6-f84c087c083b">
<img width="768" alt="Screenshot 2024-07-18 at 5 50 18 am" src="https://github.com/user-attachments/assets/c4000231-94df-4292-8918-616571a16aa6">

2024-07-18 05:16 UTC, angewen requested changes
<img width="513" alt="image" src="https://github.com/user-attachments/assets/1dc819d2-7a73-4ea0-bd16-a5a7069b1775">
<img width="526" alt="image" src="https://github.com/user-attachments/assets/d7fd0bb5-8691-46a1-879c-0bfa1770f332">

Would you be able to make sure the height of the aspect ratio changes so that it doesn't push the title below it down too much? Otherwise looks great!

2024-07-18 05:57 UTC, sophiac6410 commented on components/PageHeaderCard.tsx
> +        height: {
You can also use the keyword 'auto' so that the height changes automatically based on the width

2024-07-25 06:27 UTC, sophiac6410 approved these changes
lgtm!

2024-08-29 07:24 UTC, ammu393 approved these changes

2024-08-29 07:26 UTC, angewen approved these changes

2024-08-29 07:26 UTC, merged